//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.19 at 03:13:49 PM CET 
//


package gpw.pl.tsi.ws.definition;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for interval.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="interval"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MINUTES_5"/&gt;
 *     &lt;enumeration value="MINUTES_15"/&gt;
 *     &lt;enumeration value="MINUTES_30"/&gt;
 *     &lt;enumeration value="MINUTES_60"/&gt;
 *     &lt;enumeration value="DAY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "interval")
@XmlEnum
public enum Interval {

    MINUTES_5,
    MINUTES_15,
    MINUTES_30,
    MINUTES_60,
    DAY;

    public String value() {
        return name();
    }

    public static Interval fromValue(String v) {
        return valueOf(v);
    }

}
