//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.19 at 03:13:49 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gpw.pl/tsi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gpw.pl.tsi.ws.definition;
